/* CaliberVoice character list — the Voice page builds its cards and filters from this.
   To add a voice: copy one entry, change the fields, drop the portrait in assets/portraits/.
     gender  "Male" | "Female"
     rating  "G" | "PG" | "PG-13" | "R"
     genres  any labels — new ones show up as filter buttons on their own
     samples optional clips in assets/voice-samples/ — clicking the card plays one at random
     games   game packs this voice has (card shows the first few + a "more" toggle)
     demo    true = ships free with CaliberEngine (not shown on the card)
     steam / store  optional buy links for this voice (card shows buttons when set)
                    no links = card shows a COMING SOON badge
   Order here = order on the page. */
var CALIBER_VOICES = [
  { name: "'Shade'",       img: 'shade.jpg', samples: ['shade-1.mp3', 'shade-2.mp3'],         gender: 'Male',   rating: 'PG-13', genres: ['FPS', 'Survival', 'Co-op', 'Battle Royale'], demo: true,
    games: ["Fortnite", "Call of Duty", "Battlefield", "Counter-Strike 2", "Escape from Tarkov", "Rainbow Six Siege", "ARC Raiders", "Helldivers 2", "DayZ", "The Division 2", "STALKER 2", "Delta Force", "Squad", "Ready or Not", "Arena Breakout: Infinite", "Hell Let Loose: Vietnam", "Bodycam", "WARDOGS"],
    desc: 'Quiet, dry and hard to rattle.' },
  { name: 'ISA Officer',   img: 'isa-officer.jpg', samples: ['isa-officer-1.mp3', 'isa-officer-2.mp3'],   gender: 'Female', rating: 'PG-13', genres: ['FPS', 'Survival', 'Co-op', 'Battle Royale'], demo: true,
    games: ["Fortnite", "Call of Duty", "Battlefield", "Counter-Strike 2", "Escape from Tarkov", "Rainbow Six Siege", "ARC Raiders", "Helldivers 2", "DayZ", "The Division 2", "STALKER 2", "Delta Force", "Squad", "Ready or Not", "Arena Breakout: Infinite", "Hell Let Loose: Vietnam", "Bodycam", "WARDOGS"],
    desc: 'Calm, professional, always on the mission.' },
  { name: 'Spetsnaz',      img: 'spetsnaz.jpg', samples: ['spetsnaz-1.mp3', 'spetsnaz-2.mp3'],      gender: 'Male',   rating: 'R',     genres: ['FPS', 'Survival', 'Co-op'],
    games: ["Call of Duty", "Battlefield", "Counter-Strike 2", "Escape from Tarkov", "Rainbow Six Siege", "ARC Raiders", "Helldivers 2", "Rust", "DayZ", "The Division 2", "STALKER 2", "Delta Force", "Squad", "Ready or Not", "Arena Breakout: Infinite", "Hell Let Loose: Vietnam", "Bodycam", "WARDOGS"],
    desc: 'Terse and disciplined. Swears in Russian.' },
  { name: 'Convergence-7', img: 'convergence-7.jpg', samples: ['convergence-7-1.mp3', 'convergence-7-2.mp3'], gender: 'Female', rating: 'PG',    genres: ['Sci-Fi', 'Space', 'Factory'],
    games: ["No Man's Sky", "Starfield", "Satisfactory", "StarRupture"],
    desc: 'An assistant AI with a sharp edge.' },
  { name: 'Divergence-7',  img: 'divergence-7.jpg', samples: ['divergence-7-1.mp3', 'divergence-7-2.mp3'],  gender: 'Male',   rating: 'PG',    genres: ['Sci-Fi', 'Space', 'Factory'],
    games: ["No Man's Sky", "Starfield", "Satisfactory", "StarRupture"],
    desc: 'Androgynous and robotic, and not quite the same as Convergence-7.' },
  { name: 'Apparition',    img: 'apparition.jpg', samples: ['apparition-1.mp3', 'apparition-2.mp3'],    gender: 'Female', rating: 'PG-13', genres: ['ARPG', 'RPG', 'MMO'],
    games: ["World of Warcraft", "Mistfall Hunter"],
    desc: 'A whisper that seems to know where you are.' },
  { name: 'Phantom',       img: 'phantom.jpg', samples: ['phantom-1.mp3', 'phantom-2.mp3'],       gender: 'Male',   rating: 'PG-13', genres: ['ARPG', 'RPG', 'MMO'],
    games: ["World of Warcraft", "Mistfall Hunter"],
    desc: 'Cold, close and quiet.' },
  { name: 'Thud Boulderson',    img: 'thud-boulderson.jpg', samples: ['thud-boulderson-1.mp3', 'thud-boulderson-2.mp3'],       gender: 'Male',   rating: 'G', genres: ['RPG'],
    games: ["Everwind", "RuneScape: Dragonwilds"],
    desc: 'A big, brave hero. Not the sharpest sword.' },
  { name: 'Wren Sparkwright',   img: 'wren-sparkwright.jpg', samples: ['wren-sparkwright-1.mp3', 'wren-sparkwright-2.mp3'],     gender: 'Female', rating: 'G', genres: ['RPG'],
    games: ["Everwind", "RuneScape: Dragonwilds"],
    desc: 'A brilliant engineer. Too smart for her own good.' },
  { name: 'Barnaby Fizzlewick', img: 'barnaby-fizzlewick.jpg', samples: ['barnaby-fizzlewick-1.mp3', 'barnaby-fizzlewick-2.mp3'], gender: 'Male',   rating: 'G', genres: ['RPG'],
    games: ["Everwind", "RuneScape: Dragonwilds"],
    desc: 'A cheerful old wizard. Almost too cheerful.' },
  { name: 'The Wanderer',       img: 'the-wanderer.jpg', samples: ['wanderer-1.mp3', 'wanderer-2.mp3'],                   gender: 'Male',   rating: 'PG-13', genres: ['Survival', 'RPG', 'Strategy'],
    games: ["Valheim", "Assassin's Creed Valhalla", "ASKA", "Northgard"],
    desc: 'A Viking explorer-king. Calm, dry and always looking past the horizon. Curses in Norse/Norwegian.' },
  { name: 'The Shieldmaiden',   img: 'the-shieldmaiden.jpg', samples: ['shieldmaiden-1.mp3', 'shieldmaiden-2.mp3'],       gender: 'Female', rating: 'PG-13', genres: ['Survival', 'RPG'],
    games: ["Valheim", "Assassin's Creed Valhalla", "ASKA"],
    desc: 'Holds the line and guards the hall. Curses in Norse/Norwegian.' },
  { name: 'The Shipwright',     img: 'the-shipwright.jpg', samples: ['shipwright-1.mp3', 'shipwright-2.mp3'],             gender: 'Male',   rating: 'R', genres: ['Survival', 'RPG'],
    games: ["Valheim", "Assassin's Creed Valhalla", "ASKA", "God of War"],
    desc: 'A giggling boat-builder who talks to the gods. They talk back. Curses in Norse/Norwegian.' },
  { name: 'Ironside',           img: 'ironside.jpg', samples: ['ironside-1.mp3', 'ironside-2.mp3'],                       gender: 'Male',   rating: 'R', genres: ['Survival', 'RPG'],
    games: ["Valheim", "Assassin's Creed Valhalla", "God of War"],
    desc: 'Few words. Big axe. Keeps walking. Curses in Norse/Norwegian.' },
  { name: 'The Boneless',       img: 'the-boneless.jpg', samples: ['boneless-1.mp3', 'boneless-2.mp3'],                   gender: 'Male',   rating: 'R', genres: ['Survival', 'RPG', 'Strategy'],
    games: ["Valheim", "Assassin's Creed Valhalla", "Northgard", "God of War"],
    desc: 'A ruthless young warlord. His mind is the weapon. Curses in Norse/Norwegian.' },
  { name: 'Bosun Kaz Varga',    img: 'kaz-varga.jpg',                                                                     gender: 'Female', rating: 'R',     genres: ['Pirate'],
    games: ["Sea of Thieves", "Windrose", "Skull and Bones", "World of Sea Battle", "Corsair Cove", "Naval Action", "Assassin's Creed IV Black Flag"],
    desc: 'Best blade on any ship, and everyone knows it.' },
  { name: 'Old Quartermaster',  img: 'old-quartermaster.jpg', samples: ['old-quartermaster-1.mp3', 'old-quartermaster-2.mp3'], gender: 'Male', rating: 'R',     genres: ['Pirate'],
    games: ["Sea of Thieves", "Windrose", "Skull and Bones", "World of Sea Battle", "Corsair Cove", "Naval Action", "Assassin's Creed IV Black Flag"],
    desc: 'Keeps the books, splits the loot, locks up the rum.' },
  { name: 'Kurogane Hayato',    img: 'kurogane-hayato.jpg',                                                               gender: 'Male',   rating: 'PG-13',     genres: ['Samurai', 'Strategy', 'Survival'],
    games: ["Onimusha: Way of the Sword", "Assassin's Creed Shadows", "Ghost of Tsushima", "Total War: Shogun 2", "Sengoku Dynasty"],
    desc: 'An old masterless ronin. Weary, honorable, deadly. Curses in Japanese.' },
  { name: 'Akane Tachibana',    img: 'akane-tachibana.jpg',                                                               gender: 'Female', rating: 'R',     genres: ['Samurai', 'Survival'],
    games: ["Onimusha: Way of the Sword", "Assassin's Creed Shadows", "Ghost of Tsushima", "Sengoku Dynasty"],
    desc: 'A fierce woman warrior with a naginata and a grudge. Curses in Japanese.' },
  { name: 'Kage',               img: 'kage.jpg',                                                                          gender: 'Male',   rating: 'R',     genres: ['Samurai', 'Strategy'],
    games: ["Assassin's Creed Shadows", "Ghost of Tsushima", "Total War: Shogun 2"],
    desc: 'A sly shinobi. You never see him coming. Curses in Japanese.' },
  { name: 'Cole Harlan',        img: 'cole-harlan.jpg',                                                                   gender: 'Male',   rating: 'PG-13', genres: ['Western', 'FPS', 'Strategy'],
    games: ["Red Dead Redemption 2", "Hunt: Showdown 1896", "Desperados III", "The Legend of California"],
    desc: 'An outlaw with a price on his head and a dry sense of humor. Curses like the Old West.' },
  { name: 'Ruby Maddox',        img: 'ruby-maddox.jpg',                                                                   gender: 'Female', rating: 'PG-13', genres: ['Western', 'FPS', 'Strategy'],
    games: ["Red Dead Redemption 2", "Hunt: Showdown 1896", "Railway Empire 2", "Desperados III", "The Legend of California"],
    desc: 'Runs the Gilded Spur Saloon, and the town. Keeps a shotgun under the bar. Curses like the Old West.' },
  { name: 'Silas "Nugget" Pruitt', img: 'silas-pruitt.jpg',                                                               gender: 'Male',   rating: 'PG-13', genres: ['Western', 'Strategy', 'Survival'],
    games: ["Red Dead Redemption 2", "Railway Empire 2", "The Legend of California"],
    desc: 'An old 1849 gold miner still panning, full of tall tales. Curses like the Old West.' },
  { name: 'Aldric Stoneveil', img: 'aldric-stoneveil.jpg', gender: 'Male', rating: 'PG-13', genres: ['MMO', 'RPG'],
    games: ["World of Warcraft"],
    desc: 'A Human paladin from the Westfall farms. Warm, steady, big-brother energy. Curses in Common oaths.' },
  { name: 'Lyria Ashveil', img: 'lyria-ashveil.jpg', gender: 'Female', rating: 'PG-13', genres: ['MMO', 'RPG'],
    games: ["World of Warcraft"],
    desc: 'A Human mage trained in Dalaran. Brilliant, dry and a little superior. Curses in Common oaths.' },
  { name: 'Grommak', img: 'grommak.jpg', gender: 'Male', rating: 'PG-13', genres: ['MMO', 'RPG'],
    games: ["World of Warcraft"],
    desc: 'An old Orc shaman who talks to the elements and calls you young one. Curses in Orcish.' },
  { name: 'Zhara Stonefist', img: 'zhara-stonefist.jpg', gender: 'Female', rating: 'PG-13', genres: ['MMO', 'RPG'],
    games: ["World of Warcraft"],
    desc: 'An Orc warrior from the fighting pits. Fierce, blunt and always wants a fight. Curses in Orcish.' },
  { name: 'Tazjiri', img: 'tazjiri.jpg', gender: 'Male', rating: 'PG-13', genres: ['MMO', 'RPG'],
    games: ["World of Warcraft"],
    desc: 'A laid-back Troll rogue from the Echo Isles. Sly, grinning, never misses. Curses in Zandali.' },
  { name: 'Ojaya', img: 'ojaya.jpg', gender: 'Female', rating: 'PG-13', genres: ['MMO', 'RPG'],
    games: ["World of Warcraft"],
    desc: 'A Troll voodoo priestess who calls everyone child. Warm until you cross her. Curses in Zandali.' },
  { name: 'Durgan Ironbrew', img: 'durgan-ironbrew.jpg', gender: 'Male', rating: 'PG-13', genres: ['MMO', 'RPG'],
    games: ["World of Warcraft"],
    desc: 'A jolly Dwarf brewmaster who tanks with a keg on his back. Curses in Dwarven.' },
  { name: 'Brenna Coppervein', img: 'brenna-coppervein.jpg', gender: 'Female', rating: 'PG-13', genres: ['MMO', 'RPG'],
    games: ["World of Warcraft"],
    desc: 'A Dwarf hunter and ruin explorer with a big rifle and a ram named Clover. Curses in Dwarven.' },
  { name: 'Faelan Moonwhisper', img: 'faelan-moonwhisper.jpg', gender: 'Male', rating: 'PG-13', genres: ['MMO', 'RPG'],
    games: ["World of Warcraft"],
    desc: 'A ten-thousand-year-old Night Elf druid. Calm, ancient, gently amused by everyone. Curses in Darnassian.' },
  { name: 'Shael\'na Starbow', img: 'shaelna-starbow.jpg', gender: 'Female', rating: 'PG-13', genres: ['MMO', 'RPG'],
    games: ["World of Warcraft"],
    desc: 'A blindfolded Night Elf demon hunter. Cold, focused and relentless. Curses in Darnassian.' },
  { name: 'Fizzwick Sprocketbolt', img: 'fizzwick-sprocketbolt.jpg', gender: 'Male', rating: 'PG-13', genres: ['MMO', 'RPG'],
    games: ["World of Warcraft"],
    desc: 'A fast-talking Gnome warlock who treats demons like lab equipment. Curses in gnome tech-talk.' },
  { name: 'Tilly Gearspin', img: 'tilly-gearspin.jpg', gender: 'Female', rating: 'PG-13', genres: ['MMO', 'RPG'],
    games: ["World of Warcraft"],
    desc: 'A cheerful Gnome death knight with a ghoul named Bolts. Undead and happy about it. Curses in gnome tech-talk.' },
  { name: 'Voren', img: 'voren.jpg', gender: 'Male', rating: 'PG-13', genres: ['MMO', 'RPG'],
    games: ["World of Warcraft"],
    desc: 'A 25,000-year-old Draenei warrior. Solemn, noble, done running. Curses in Draenei.' },
  { name: 'Talanya', img: 'talanya.jpg', gender: 'Female', rating: 'PG-13', genres: ['MMO', 'RPG'],
    games: ["World of Warcraft"],
    desc: 'A young Draenei shaman who hears the elements like music. Gentle and protective. Curses in Draenei.' },
  { name: 'Edmund Greyfang', img: 'edmund-greyfang.jpg', gender: 'Male', rating: 'PG-13', genres: ['MMO', 'RPG'],
    games: ["World of Warcraft"],
    desc: 'A grumpy Worgen huntsman from Gilneas with a rifle and a crow. Curses in old Gilnean oaths.' },
  { name: 'Lady Beatrix Thorne', img: 'lady-beatrix-thorne.jpg', gender: 'Female', rating: 'PG-13', genres: ['MMO', 'RPG'],
    games: ["World of Warcraft"],
    desc: 'A Worgen noblewoman with two pistols. Perfectly polite while doing terrible things. Curses in old Gilnean oaths.' },
  { name: 'Mortimer Gravesend', img: 'mortimer-gravesend.jpg', gender: 'Male', rating: 'PG-13', genres: ['MMO', 'RPG'],
    games: ["World of Warcraft"],
    desc: 'A cheerful Undead warlock who used to dig graves. Bits fall off when he laughs. Curses in Forsaken slang.' },
  { name: 'Seraphyne', img: 'seraphyne.jpg', gender: 'Female', rating: 'PG-13', genres: ['MMO', 'RPG'],
    games: ["World of Warcraft"],
    desc: 'An Undead shadow priest who was once a court singer. Whispers and hums mid-fight. Curses in Forsaken slang.' },
  { name: 'Harn Earthhoof', img: 'harn-earthhoof.jpg', gender: 'Male', rating: 'PG-13', genres: ['MMO', 'RPG'],
    games: ["World of Warcraft"],
    desc: 'A huge, gentle Tauren paladin. Slow to anger, unstoppable once angry. Curses in Taur-ahe.' },
  { name: 'Lumara Skyhorn', img: 'lumara-skyhorn.jpg', gender: 'Female', rating: 'PG-13', genres: ['MMO', 'RPG'],
    games: ["World of Warcraft"],
    desc: 'A Tauren druid healer who mothers the whole raid. Don\'t stand in fire. Curses in Taur-ahe.' },
  { name: 'Vaelis Sunfire', img: 'vaelis-sunfire.jpg', gender: 'Male', rating: 'PG-13', genres: ['MMO', 'RPG'],
    games: ["World of Warcraft"],
    desc: 'A vain, dramatic Blood Elf paladin who fixes his hair mid-fight. Brave underneath. Curses in Thalassian.' },
  { name: 'Liora Brightflame', img: 'liora-brightflame.jpg', gender: 'Female', rating: 'PG-13', genres: ['MMO', 'RPG'],
    games: ["World of Warcraft"],
    desc: 'A fiery Blood Elf monk who heals with kicks and tea. Curses in Thalassian.' },
  { name: 'Rizzo "Two-Coins" Gearlock', img: 'rizzo-gearlock.jpg', gender: 'Male', rating: 'PG-13', genres: ['MMO', 'RPG'],
    games: ["World of Warcraft"],
    desc: 'A Goblin death knight who died in a bad deal and kept selling. Calls his undead army free labor. Curses in goblin money-talk.' },
  { name: 'Jinx Boomwrench', img: 'jinx-boomwrench.jpg', gender: 'Female', rating: 'PG-13', genres: ['MMO', 'RPG'],
    games: ["World of Warcraft"],
    desc: 'A Goblin fire mage who rates every explosion out of ten. Curses in goblin money-talk.' },
  { name: 'Korrin Deepgrumble', img: 'korrin-deepgrumble.jpg', gender: 'Male', rating: 'R', genres: ['Survival', 'Co-op'],
    games: ["The Lord of the Rings: Return to Moria", "Deep Rock Galactic"],
    desc: 'A 300-year-old dwarf miner, half-deaf and half-drunk, with stories that never end. Still deadly. Curses like a sailor.' }
];
